### PR TITLE
no: New default APN for Telenor Norway

### PR DESCRIPTION
**Pull request by toreanderson**
Telenor Norway's new APN is "telenor.smart". This APN supports both IPv4
and IPv6, so it is necessary to use a hostname rather than a literal
IPv4 address for the MMS proxy setting. Also remove the statically
configured DNS servers; Telenor is using dynamic DNS server assignment
(and the DNS servers they currently assign are in any case different
from the ones currently hard-coded in serviceproviders.xml).

This change has been ACK-ed by Telenor's IPv6 project leader
Gwenael-Christian Berthet <Gwenael-Christian.Berthet@telenor.com>.

The new settings may be verified on Telenor's web pages at
http://www.telenor.no/privat/kundeservice/mobilhjelp/ (under "Kom i gang
med IPv6").

### CODE REVIEW

**Comment by tigeli** [comment]
LGTM

**Comment by toreanderson** [comment]
Updated commit message with [mbpi] prefix. I also noted the fact that the new APN do not require username/password.

**Comment by monich** [comment]
Unfortunately DNS resolution over MMS PDP context doesn't work in Jolla. IP address is required for MMS proxy.

**Comment by toreanderson** [comment]
Ok, I've now reverted that part of the change. Does that look better? As long as the UE requests a dual-stack PDP context (or two parallel IPv4-only and IPv6-only PDP contexts), the IPv4 literal should work even though it is not Telenor's officially recommended configuration.

(That said, lack of name resolution does seem like a bug that needs fixing, especially considering that other providers are deploying IPv6-only networks.)

**Comment by monich** [comment]
DNS resolution is handled by connman which is not aware of MMS context coming up or down. I have to admit that lack of DNS resolution is indeed a bug or perhaps a missing feature, depending on how you look at it. In any case it needs to be fixed.

Thanks for your contribution.

**Comment by toreanderson** [comment]
If you consider the lack of DNS support a missing feature rather than a bug, then you should consider the fact that the user interface allows you to input a host name a bug instead. Since getting my Jolla I've had difficulty making MMS work correctly. I simply entered `mms-proxy.telenor.no:8080` as the MMS proxy address (which, after all, is *exactly* what Telenor tells me to), and this was accepted without any warnings. It does seem likely that this was the reason why I had problems making it work.

Another thing that strikes me as somewhat weird is that SailfishOS seems to insist on using a separate PDP context for MMS. Telenor uses a single APN for both data and MMS; therefore there should be no reason to establish a separate PDP context for MMS - it seems simpler to me to use the already existing one (which happens to have working DNS resolution too). For what it's worth this is how Android seems to do it; you only configure a single APN and configure it with `type=default,mms`.

In any case, thanks for merging my patch!

**Pull request merged**
