### PR TITLE
Update settings for 3 UK

### PR DESCRIPTION
**Pull request by monich**
Verified with the actual customer that it does work.

### CODE REVIEW

**Comment by tkenakka** [comment]
LGTM
Btw were you able to check from somewhere if the "3internet" is anymore used by any 3UK subscription?

**Comment by monich** [comment]
I don't mind removing "3internet"

**Comment by tkenakka** [comment]
I was wondering more could some subscriptions use the old one and thus their default resolving break when the first in list changes. 
In this specific case I don't have better info, it was just a question because some operators have had different sets for different subscriptions.

**Comment by monich** [comment]
Let's leave it alone then

**Pull request merged**
